# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('client_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('employee_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('project_name', models.CharField(max_length=30)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.Client')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('timesheet_date', models.DateField()),
                ('timesheet_hours', models.CharField(max_length=2)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.Employee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetapp.Project')),
            ],
        ),
    ]
