# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0005_auto_20180706_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_dow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_week',
            field=models.IntegerField(null=True),
        ),
    ]
