# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0007_auto_20180712_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_contract_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_purchase_order',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_wbs',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
