# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetapp', '0008_auto_20180829_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
